### ISSUE TITLE
Module not found: Can't resolve 'a' in  '\node_modules\deepar\wasm'

### ISSUE THREAD

**Issue by fatihozdil** [DeepARSDK/quickstart-agora-web-extension#1]
When I try to extract Deepar.wasm I get the error in the title. I'm trying to do this on react. My main purpose is to connect the deepar with the agora. I installed the deepar-agora-extension package via npm as stated in the documentation. I think the 'deepar' package is also installed when I install this package, because I can see it in node_modules. I did the webpack configuration like below.
![image](https://user-images.githubusercontent.com/72515197/200535163-c05bb35b-7938-4c1d-867e-6978e7430978.png)

```const path = require("path");

module.exports = {
  entry: "./src/index.js",
  output: {
    filename: "main.js",
    path: path.resolve(__dirname, "dist"),
    clean: true,
  },
  target: "web",
  module: {
    rules: [
      {
        test: /\.(wasm)|(bin)|(obj)$/i,
        loaders: ['wasm-loader'],
        include: [path.resolve(__dirname, "node_modules/deepar/")],
        // use: {
        //   loader: "babel-loader",
        //   options: ["@babel/preset-env", "@babel/preset-react"],
        // },
        type: "asset/resource",
      },
      //   {
      //     include: [
      //       path.resolve(__dirname, 'effects/'),
      //     ],
      //     type: 'asset/resource',
      //   },
    ],
  },
  //   resolve: {
  //     alias: {
  //       '@effects': path.resolve(__dirname, 'effects/'),
  //     },
  //   },
  performance: {
    maxEntrypointSize: 1000000,
    maxAssetSize: 10000000,
  },
};
```  
- Since I am using webpack version 4, I also wrote the following codes in the config override file.

```
const path = require('path')

module.exports = function override (config, env) {
  const wasmExtensionRegExp = /\.wasm$/
  config.resolve.extensions.push('.wasm')
  config.module.rules.forEach(rule => {
    (rule.oneOf || []).forEach(oneOf => {
      if (oneOf.loader && oneOf.loader.indexOf('file-loader') >= 0) {
        oneOf.exclude.push(wasmExtensionRegExp)
      }
    })
  })

  config.module.rules.push({
    test: wasmExtensionRegExp,
    include: path.resolve(__dirname, 'src'),
    use: [{ loader: require.resolve('wasm-loader'), options: {} }]
  })

  return config
}
```  
  
I also changed npm start command in the package.json like below
`
  "scripts": {
    "start": "react-app-rewired start",
    "build": "react-app-rewired build",
    "test": "react-scripts test",
    "eject": "react-scripts eject"
  },`

- Since I've used deep ar before, I looked for another way to find a solution, because I used deepar.wasm file before, I had it directly, I tried to import it, but I encountered the below error again.

> Uncaught (in promise) RuntimeError: Aborted(LinkError: WebAssembly.instantiate(): Import #358 module="a" function="memory" error: memory import must be a WebAssembly.Memory object). Build with -sASSERTIONS for more info.
    at X (deepar-agora-extension.js:1:1)
    at deepar-agora-extension.js:1:1

**Comment by DishoD** [comment]
Make sure to update the DeepAR Agora Extension to the latest version (and the deeper dependency also).

I see that you are using `wasm-loader` for loading wasm file. That loader is intended for something else. Use a loader for plain binary files like we did in our webpack config. 

```js
rules: [
      {
        test: /\.(wasm)|(bin)|(obj)$/i,
        include: [
          path.resolve(__dirname, 'node_modules/deepar/'),
        ],
        type: 'asset/resource',
      },
```

**Comment by fatihozdil** [comment]
`    "deepar": "^4.0.2",
    "deepar-agora-extension": "^1.0.1",`
versions of packages as above.

_webpack.config.js_
```
const path = require("path");

module.exports = {
  entry: "./src/index.js",
  output: {
    filename: "main.js",
    path: path.resolve(__dirname, "dist"),
    clean: true,
  },
  target: "web",
  module: {
    rules: [
      {
        test: /\.(wasm)|(bin)|(obj)$/i,
        include: [path.resolve(__dirname, "node_modules/deepar/")],
        type: "asset/resource",
      },
    ],
  },
}
```

- If I don't use wasm-loader, I get the following error.

> ./node_modules/deepar/wasm/deepar.wasm
Module parse failed: magic header not detected
File was processed with these loaders:
 \* ./node_modules/file-loader/dist/cjs.js
You may need an additional loader to handle the result of these loaders.
Error: magic header not detected

-  As a solution to this, I thought of writing a config override.  

_config.overrides.js_
```
const path = require('path')

module.exports = function override (config, env) {
  const wasmExtensionRegExp = /\.wasm$/
  config.resolve.extensions.push('.wasm')
  config.module.rules.forEach(rule => {
    (rule.oneOf || []).forEach(oneOf => {
      if (oneOf.loader && oneOf.loader.indexOf('file-loader') >= 0) {
        oneOf.exclude.push(wasmExtensionRegExp)
      }
    })
  })

  config.module.rules.push({
    test: wasmExtensionRegExp,
    include: path.resolve(__dirname, 'src'),
    // use: [{ loader: require.resolve('wasm-loader'), options: {} }]
  })

  return config
}
```
-  I still get the error 

> "Module not found: Can't resolve 'a' in '\node_modules\deepar\wasm"  

in the title even if I use wasm-loader in the config override file or not

**Comment by DishoD** [comment]
As I said, you need to load the file as plain binary and ignore that it is a wasm file at all.
If you can't load it with webpack loaders, you can manually copy the wasm file to dist folder and pass the appropriate path to the DeepAR constructor.

I'm closing this issue since it is webpack related and not an issue of this repository.
